language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: j4GwCn6Y24xXENKEbGlNyoTzZnYqqQV/WmcA9+dlcn4ynebuBT+ymVD180pagIYR7QTeK7WtXk2W4o+mu2Fck2urC5GuP7W1tr1eZ6UFqasqiig9QgEd9rWM2dsSu9mjCFiyBPgZdTJBDBmvvzBRjck/ev9gzeQLhg44O+zX5AMKIMc3U6AwzLy/iw2INaPJSeJCOj5VpiNlkCTUW6UQ/0LYkNxuFTm5N3Cr0xdmFkABOzUkC+I1huhAzFU180xCpNSqeKWpw5ekid+lWCIyOrOQvKdjEb8rl0dZGMGLFZpol92/P8eKstohw6N3nlprBCBiL8nf64ZL5SWsRUu0J6+NEq5lWhS4JAwihEiGg02l68z7+3IRB8xDEe1AuNMk4Xdmg8ds219fMWbp1cVmLndZ28laHbxvT2NtDVJ4tN46Vyfw1rW1G50VRRWWEfuF81fo8LGCD6Cmd7BFsD7bBZKZjSNPYpLGdx5HUcx3XRBG50/KxlRPB2vTZa2wytTH/sI6cvSWM14ONHkTlrFfgCzA2ELUZEIPw0DbpU2NYpYeb26/bfpxMg5tAtadMbYL0JyPdaf23FHpeyjQvmb3lS8UoXZmLqcqNMn0c/4hCV/+nFU5hzAWdoBE4euq2SKPoJ0tCB03X6QH4T8T8/gF/e2tZkoKFS06/jB5uiaEIbE=
  - secure: Ba4enFQ7WhHI1/q8njdlMY2/7sQmIzDtirWkiQOVRTPNrF+fdtSicG3tHjznd1Gz5wbqkG1LmlaqAhcPh3Lrd2FLE5+VP9awDcjmBYOsed+2RKx0z3fXvzTl8rkwctSxwpA6vyeWbWcPS7tfmrcT7+hjMk9LFmFhM6pXqP0j0ks2HAVDkaO8qaq4edqnY3OVAFl/EmwImyyh6GcAmordswtMmYcq34DFWRtr10U+XFalzBanqijjzBPighQYVHZ9W7GATIFjhoEzjgCGzr4raaEFyeYJyj19UiHhMvPlFNvn1G/jc5wu0YISrUHQuNBHSQcySpslBgvEPTFWU/zDG9Am0SK6YbgVc3O6Yw0Y7UFadMK372jP9UeBWdzj9emyqDnzBJBsRSvKcfSNJhLhGI8xf6WjOjDmMi7vXSMBI1a5sOZIh35YdmHTN+7tV0fIvpRqbt5SfBjMIxDMn5ORlZ2QPpc+/hGmw9+m7mwxOaU0/laOs96h4+JjEjAwQ+6px2fkrZwhAo46nk+lGuBYZZA0PMf8+8NbBnrEGf5eAAHdN8ZjB17IMJdAaGgg21Xvus6vaioqmB+9UWbgLdZHQnE+Ks4tP77gzBH7xTSMkM8rRCTBvB/udTBPd+ej1lCjSqQBvPomp6Ad99do8+U739vYGDFW1YPk15+tbZdoUeY=
  - secure: K5PG8YGppGwfut64D5ltBnpP74lFdM59LvaA3Qclihl+iE3HfjVK6DMDVNopFMwVTqlI4I5Qh+P5VVN7hHp4xLepJNFJqmCEOM1EKFIoE6GcCyC99jJAsKALQwXe1iB9UWoiNksKE2LwYVRTO/M/gao1dVGhx/aIGY8A+nWyI1ptwV7CErEyFGnRh166kGbS5PX0IwZzpeNOUJSeBAkRBIylshPsyeB5r0N1lHwH5RS9XYKP2dSDKvUU9zbabBYjBJ4whUdKX22rnE8RVnjfDkD6Z4d2e7g6cx4I9rnBr23oZiCG5sDGbDsvirDmu6KXCnQ69Wqk20n90qhHe1dl9dL5lByEkjkGOEojFqnHjrEyK/e2oC6NPg11wxvsbQ+drAZPbElahcZsKoh+AxFpGeBpjEnkj4GbpD9EBfATIGzRpmbitPoCaGr5NwvfpIW49l0EK3DK9ZhPJsDe0K1t4M67UZdXNhK/kXSwdfeqQNdKpO8SO7OGpyvlGpISbJZu4gWkiN9fc0hJbmo9Nut8z+sNLcliIvO2uCqP84hc3q90pta8C1OuvwqxBSVmRw91f5Bh0N6SxbPDH9JQpCNscuV9GPKghy2ASdJeBwmHFF+HnZTqep7p8/qO/L2zUqTfscBfzDxdKpG52V1Vi9VDGl5MFJfiFqbin6zrT3hN2kU=
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_45ceee9b8c21_key -iv $encrypted_45ceee9b8c21_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
