language: python
python:
- '3.6'
install:
- pip install ansible==2.3.0 molecule apache-libcloud
env:
  matrix:
  - GCE_CREDENTIALS_FILE="$(pwd)/credentials.json"
  global:
  - secure: RbPW/hbUtrYcb/QCrLNyilslpWAEKvXd/ka6vEDKOHxBX0AATtKo1SqLMwJTCKhz1Yvljctt2rSwlxIzml1rGELA6t0A1o/2TBkL2cTpc69B7KmZXetF5ZCBzW1xoKBoef0yCz1nW2+7U38zcLCPlpY3L7Wg/JldEY9CPMMze+Jd50zsQegF5IA0FOHuxyYa0EtYu5CKU8OBO22VQKUUNOu4dGAH8+ZBmBuLBX73hMy5xcPo7iWDVuX84VmUBPdm4XghhpgCckq+SXlDm/d2iCVS0uYnVQjFjgsPFtt9s2vwEjo7zRFUKcjZBnDgUX9vc/N08Oa1NDQ5S3oe1BDZFGTOBmEOk2LcENbIWIZs7/PqInMUXP/a2eD9u7ZSxdH9p4edhPvyT6aQzu9A9LN8DGFtsFIK5HsthIaRjfbUndEbUc3qcW+7gutu9FwOw+NwsubdKjxjy196+gc1YhuGVr4tHgNYe8WpeUYiiIXsJD+ntjqkmqCO7Z25DYo80ufkjj3H5stLvaESGkrGcmnfnhoJDMMYUNYpIz31Rn5aRMe4Mhsxxw3pDUU0YKW4TKtalOW4mBMg5uQjqeMs+oSCrIQ9+8zADqISIu7V7ZmTkhL8AQ1/QQ7QJWHYwpBA/lm1S7j+oF2QghqOtrMn1/pIxY7iDFbJbKQa72LnQgBmkZY=
  - secure: Joc0mvit/2HHHcir210QyDv/AYjMByU07r5Y5dIulb9KC7Nh+qq6XjEG32HKnJ0Bzvk+51dCD+t+/W/wpOzR3FR0R2R63gXS8dir65/UTpOWpH1XBCuwBfdVqSyTxtmx2XdmJS3YMj6hdSxx+wynXi9xBl4GsLKqhudHzAOglynuqpUFTADN1j9uxQWejCyjCgNI202Vluiw0Aaq1Sd5FP1jN933C4J3mdok0K1UhapcJrokWFNdOcuGb3WhK4K+YBFnbAq25dKSd7BiNtsXyWoJtPjnPGAw35NtYT9SxYVkAndYz7XRl6B+ANBkrxoMEsjWE3oljSEgjwP7n4VrARGkxcCUzUIfWkrbG6eIIgcG3wAYaSwGLhT7lYvuRq7BJ6LnzRjGsCUbhVXTRin3vXdtz720S9yvN77HoENhRtg1PLu3ZimumiOVXDUsaRNYXcZm3vjPnsIcIywnJyv5ouvnHqFWRkNPmgr7fe92TG8lhEIBexmgXCy53GBGpNVrW2Rg6JxS6Ki70i8ISwprk8BPe/IaHknbWLtkEuczWgw8pLVTJ2YXnSswk+wDamrXaKzICOMDkSEkhYnPgeA8paRT8yBAI6Td1UFsyLZiQi/HEDoMc+U7gchCODehJ7AFAHzYc0gb7bKQwzcjqE+LUOmK6AEbcM4YhT7h0phXNdA=
  - secure: IC5S59qt0k6MV51EcNLkdwhA5VLrjupMQ/xQ4W0YRsZQnNtsn7cYUBELLuy3eYw0hCTGlIfnsJlsOvzV7ZIt6S+9ua2nBeQ3UEC6HAGVu7F3VtC9C0irmW00j6w5NBJZvW7MmzaM8fvCC64QZf/YuQoODxXZ7VuyHsePaymVDFiXL9JSB8vVBqnCJVx8f+XAlzpaxnDhFf1/NRUGgbnaAvBtXbtz9QlqwtdSQC+P1NsGh3CIUXOQJOdrQ5oDNe5EcUXuZp92JTWABOQuuwZ/rTFJU7iRzTqhqFCdDH9hJDTQc3UtqrIAlVqB7rlWQ3UcNcE7EBJnKyGZf5BARTMK9eAzCp2iOTf/mgC4MFW5reKzDSjDPXwajo6Oas7w0q+NZo/9PXp4SdIZI1vVOkIhbN5uTSip9Mo/ezlmCZkAbVTy2zBeYuaCQQn7ZmZhEK4eo9RLRXiFQ0IeK2NgAHl5ewc1GugHA7or+gZbH/neu9FTunEqLtnMKLxgroXqO6NOlM8jaxj4e5Ycqf5KoARaAzJftWf/0Z89cTsg2IE9jIR0PDO/R11nIxRYuev3gSOCCcQNS0mocdsd57NFgziEYWpm2GX2rM55itmgr/mp4tzwmDOjvZCKw+bqN+MyR5ImlIfSTT+Ga0cXQVFtw+BQs+PvwJi1Sdoqc9ku1pwFyzw=
script:
- molecule --debug create
- molecule --debug converge
- molecule --debug verify
after_script:
- molecule --debug destroy
before_install:
- openssl aes-256-cbc -K $encrypted_e615753abb37_key -iv $encrypted_e615753abb37_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- mv google_compute_engine /home/travis/.ssh/
- chmod 0600 /home/travis/.ssh/google_compute_engine
